blank_issues_enabled: false
contact_links:
  - name: Contacts
    email: Artim.Meyer@stundent.tu-freiberg.de
    email: Simon.Hoertzsch@student.tu-freiberg.de
    about: If you have questions, reach out to us via email.
